Apply renovate patches and update the project to support netbox-docker 3.0.1
wastrachan/ansible-role-netbox-docker pull request #17
Opened 2024-09-11 19:14 UTC by jsenecal

#### Breaking changes
- Removal of the now unsupported `netbox_napalm_*` variables
- Uses valkey instead of redis due to licence changes

#### Features
- Replaces `netbox_proxy_network_name` (a string) with `netbox_additionnal_network_names` (a list) to allow for different scenarios
- Updates the docker-compose file to add upstream health checks.

2024-09-11 19:14 UTC, jsenecal commented
Fixes #16

2024-09-11 20:03 UTC, wastrachan requested changes
Thanks for contributing all of this work, I appreciate all of the updates and the generic re-implementation of external networks. 

I'd like to understand the switch from Redis a little better. I'm aware of their license changes, as well as the impact they have on the SAAS ecosystem, as well as for various MSP uses. I also fully support the right of an individual to choose an alternative open source project when they disagree with a decision and when it suits their needs. 

Is there something about the new Redis license that makes it _incompatible_ with this project, or this project's license? Many of us rely on the stability and proven history of Redis in production workloads, and aren't yet ready to move to another offering that has not yet had ample time to prove it's development practices and stewardship. If there is an incompatibility, I'm of course happy to honor licenses and commit to removing Redis from this project, but if it's just preference- I'd prefer keeping things as they are, or perhaps exploring an option that would let the end user opt for Redis or Valkey as it fits their goals.

2024-09-11 20:03 UTC, wastrachan commented on README.md
> +| `netbox_additionnal_network_names`                   | -                             | Extra external networks to attach to the netbox container. See [Traefik/nginx-proxy Support](#traefiknginx-pro
```suggestion
| `netbox_additional_network_names`                   | -                             | Extra external networks to attach to the netbox container. See [Traefik/nginx-proxy Support](#traefiknginx-proxy-support)                                 |
```

2024-09-11 20:03 UTC, wastrachan commented on README.md
> +This playbook can be used with [traefik](https://hub.docker.com/_/traefik) or jwilder's [nginx-proxy](https://hub.docker.com/r/jwilder/nginx-proxy) by adding labels with `netbox_container_labels`, or
```suggestion
This playbook can be used with [traefik](https://hub.docker.com/_/traefik) or jwilder's [nginx-proxy](https://hub.docker.com/r/jwilder/nginx-proxy) by adding labels with `netbox_container_labels`, or environment variables with `netbox_container_env`, respectively. Additionally, `netbox_additional_network_names` will attach the netbox service to additional networks, as traefik/nginx-proxy usually reside in a network other than that created by docker-compose projects. While not a complete guide to these services, your configuration may look like the below:
```

2024-09-11 20:03 UTC, wastrachan commented on README.md
> +  - traefik
```suggestion
netbox_additional_network_names: 
  - traefik
```

2024-09-11 20:03 UTC, wastrachan commented on README.md
> +netbox_additionnal_network_names:
```suggestion
netbox_additional_network_names: 
```

2024-09-11 20:03 UTC, wastrachan commented on templates/docker-compose.yml.j2
> +    {% if netbox_additionnal_network_names %}
```suggestion
    {% if netbox_additional_network_names %}
```

2024-09-11 20:03 UTC, wastrachan commented on templates/docker-compose.yml.j2
> +      {% for network in netbox_additionnal_network_names %}- {{ network }}{% endfor %}
```suggestion
      {% for network in netbox_additional_network_names %}- {{ network }}{% endfor %}
```

2024-09-11 20:03 UTC, wastrachan commented on templates/docker-compose.yml.j2
> +{% if netbox_additionnal_network_names %}
```suggestion
{% if netbox_additional_network_names %}
```

2024-09-11 20:03 UTC, wastrachan commented on templates/docker-compose.yml.j2
> +{% for network in netbox_additionnal_network_names %}
```suggestion
{% for network in netbox_additional_network_names %}
```

2024-09-12 14:52 UTC, jsenecal commented
> Is there something about the new Redis license that makes it _incompatible_ with this project, or this project's license? Many of us rely on the stability and proven history of Redis in production workloads, and aren't yet ready to move to another offering that has not yet had ample time to prove it's development practices and stewardship. If there is an incompatibility, I'm of course happy to honor licenses and commit to removing Redis from this project, but if it's just preference- I'd prefer keeping things as they are, or perhaps exploring an option that would let the end user opt for Redis or Valkey as it fits their goals.

Under the new license, cloud service providers hosting Redis offerings will no longer be permitted to use the source code of Redis free of charge. For example, cloud service providers will be able to deliver Redis 7.4 only after agreeing to licensing terms with Redis, the maintainers of the Redis code. These agreements will underpin support for existing integrated solutions and provide full access to forthcoming Redis innovations.

This also means that a service provider cannot freely distribute a solution with a Redis component under this new licensing. 

Valkey is a FOSS fork of Redis backed by the Linux Foundation. 

This change also follows upstream decision to move away from Redis. https://github.com/netbox-community/netbox-docker/pull/1203

2024-09-16 01:34 UTC, wastrachan commented
> > Is there something about the new Redis license that makes it _incompatible_ with this project, or this project's license? Many of us rely on the stability and proven history of Redis in production workloads, and aren't yet ready to move to another offering that has not yet had ample time to prove it's development practices and stewardship. If there is an incompatibility, I'm of course happy to honor licenses and commit to removing Redis from this project, but if it's just preference- I'd prefer keeping things as they are, or perhaps exploring an option that would let the end user opt for Redis or Valkey as it fits their goals.
> 
> Under the new license, cloud service providers hosting Redis offerings will no longer be permitted to use the source code of Redis free of charge. For example, cloud service providers will be able to deliver Redis 7.4 only after agreeing to licensing terms with Redis, the maintainers of the Redis code. These agreements will underpin support for existing integrated solutions and provide full access to forthcoming Redis innovations.
> 
> This also means that a service provider cannot freely distribute a solution with a Redis component under this new licensing.
> 
> Valkey is a FOSS fork of Redis backed by the Linux Foundation.
> 
> This change also follows upstream decision to move away from Redis. [netbox-community/netbox-docker#1203](https://github.com/netbox-community/netbox-docker/pull/1203)

Thanks, this is helpful. I generally undestand the ramifications of the new license-- but knowing that Netbox has switched offers me at least the assurance that Nextbox will be continuously tested with Valkey.

2024-09-16 01:35 UTC, wastrachan approved these changes

2024-09-16 01:35 UTC, merged